# Generated by Django 6.0.7 on 2026-07-31 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('Electricista', 'Electricista'), ('Plomero', 'Plomero'), ('Albañil', 'Albañil'), ('Pintor', 'Pintor'), ('Carpintero', 'Carpintero'), ('Jardinero', 'Jardinero'), ('Programador', 'Programador'), ('Diseñador', 'Diseñador'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=120)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
