# Generated by Django 6.0.7 on 2026-07-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={},
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='creador',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trabajos/'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
