# Generated by Django 6.0.7 on 2026-08-01 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_aceptados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ACEPTADO', 'Aceptado'), ('FINALIZADO', 'Finalizado')], default='DISPONIBLE', max_length=20),
        ),
    ]
