# Generated by Django 6.0.7 on 2026-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_trabajo_aceptado_por_trabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='horas_estimadas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
