# Generated by Django 6.0.7 on 2026-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_trabajo_aceptado_por_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
