# Generated by Django 6.0.7 on 2026-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.png', upload_to='perfiles/'),
        ),
    ]
