# Generated by Django 6.0.7 on 2026-08-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci_dorso',
            field=models.ImageField(blank=True, null=True, upload_to='ci/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci_frente',
            field=models.ImageField(blank=True, null=True, upload_to='ci/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
