# Generated by Django 6.0.7 on 2026-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_ci_dorso_usuario_ci_frente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='selfie_ci',
            field=models.ImageField(blank=True, null=True, upload_to='ci/'),
        ),
    ]
